server:
  port: 8080

spring:
  application:
    name: reverse-proxy-service-backend # 需要修改
  profiles:
    active: dev # 表示开发环境
  datasource:
    url: jdbc:mysql://api.alphal.cn:52101/reverse_proxy_services?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Liang1992@12
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema:
      - classpath:sql/schema.sql
      - classpath:sql/data.sql

mybatis:
  mapper-locations: classpath:mappers/*.xml # 扫描 mapper 文件
  type-aliases-package: com.example.reverseProxyServiceBackend.entity # MyBatis 去哪个包下面找 实体类
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl